# To run the Archive in docker for the first time you should run one of the init scripts:
# - linux: `script/docker/init.sh`
# - windows: `script/docker/init.cmd`
#
# This will handle setting up config files, creating databases, and running migrations.
#
# After these oneoff tasks have been performed, you can start the development
# webserver with the command:
#
# ```
# docker compose up -d web
# ```
#
# Once it is running, it will be visible at http://localhost:3000/
#
# To run tests, you should use the test container instead of the web container,
# because it includes a headless chrome container for running JS-based tests.
# You can run tests like this:
#
# ```
# docker compose run --rm test bundle exec cucumber features/other_a/autocomplete.feature
# ```

services:
  db:
    image: mariadb:10.5.4-focal
    command:
      [
        "mysqld",
        "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ../db:/var/lib/mysql:rw

  redis:
    image: redis:5
    volumes:
      - ../redis:/var/lib/redis:rw
    healthcheck:
      test: redis-cli ping | grep PONG || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ../es:/usr/share/elasticsearch/data:rw
    environment:
      transport.host: localhost
      bootstrap.memory_lock: false
      ES_JAVA_OPTS: "-Xms1500m -Xmx1500m"
      discovery.type: single-node
      # Silence "security features are not enabled" warnings
      # https://github.com/elastic/elasticsearch/issues/78500
      xpack.security.enabled: false

  mc:
    image: memcached:1.5
    healthcheck:
      test: echo "version" | (exec 3<>/dev/tcp/localhost/11211; cat >&3; timeout 0.1 cat <&3; exec 3<&-)
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
      - es
      - mc
    ports:
      - "3007:3000"
    environment:
      # RAILS_ENV: development
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true
    healthcheck:
      test: curl -s http://localhost:3000 >/dev/null || exit 1
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/otwa
    networks:
      - default
      - web
    # Make `docker compose attach web` work for debugging
    stdin_open: true
    tty: true
    labels:
      caddy: ao3.boreas.planetkamran.com, ffa.boreas.planetkamran.com
      caddy.reverse_proxy: "{{upstreams 3000}}"

  worker:
    image: otwarchive-web:latest
    command: bash -c "QUEUE=* bundle exec rake environment resque:work --trace"
    depends_on:
      - db
      - redis
      - es
      - mc
      - web
    environment:
      RAILS_ENV: production
    volumes:
      - .:/otwa

  scheduler:
    image: otwarchive-web:latest
    command: bash -c "QUEUE=* bundle exec rake resque:scheduler --trace"
    depends_on:
      - db
      - redis
      - es
      - mc
      - worker
    environment:
      RAILS_ENV: production
    volumes:
      - .:/otwa

  chrome:
    profiles:
      - test
    image: selenium/standalone-chromium

  test:
    profiles:
      - test
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    environment:
      - RAILS_ENV=test
      - CHROME_URL=http://chrome:4444
      - DOCKER=true
      - CAPYBARA_PORT=5100
    command: bundle exec cucumber
    volumes:
      - .:/otwa
    depends_on:
      - db
      - redis
      - es
      - mc
      - chrome

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token changeme2
    depends_on:
      - web
    restart: always
    environment:
      TZ: America/Los_Angeles

networks:
  default:
  web:
    external: true
